# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocolo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotocolo.proto\x12\x08messages\"\x1a\n\tFindTitle\x12\r\n\x05title\x18\x01 \x01(\t\" \n\x0c\x46indCategory\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"\x1a\n\tFindActor\x12\r\n\x05\x61\x63tor\x18\x01 \x01(\t\"\xf9\x01\n\x05Movie\x12\x0c\n\x04plot\x18\x01 \x01(\t\x12\x0e\n\x06genres\x18\x02 \x03(\t\x12\x0f\n\x07runtime\x18\x03 \x01(\x05\x12\x0c\n\x04\x63\x61st\x18\x04 \x03(\t\x12\x1a\n\x12num_mflix_comments\x18\x05 \x01(\x05\x12\r\n\x05title\x18\x06 \x01(\t\x12\x10\n\x08\x66ullplot\x18\x07 \x01(\t\x12\x11\n\tcountries\x18\x08 \x03(\t\x12\x10\n\x08released\x18\t \x01(\t\x12\x11\n\tdirectors\x18\n \x03(\t\x12\r\n\x05rated\x18\x0b \x01(\t\x12\x13\n\x0blastupdated\x18\x0c \x01(\t\x12\x0c\n\x04year\x18\r \x01(\x05\x12\x0c\n\x04type\x18\x0e \x01(\t\"/\n\x0c\x46indResponse\x12\x1f\n\x06movies\x18\x01 \x03(\x0b\x32\x0f.messages.Movie\"7\n\x06\x43reate\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\x10\n\x08\x66ullplot\x18\x03 \x01(\t\"8\n\x06Update\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1f\n\x06movies\x18\x02 \x01(\x0b\x32\x0f.messages.Movie\"\x17\n\x06\x44\x65lete\x12\r\n\x05title\x18\x01 \x01(\t\"\x17\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xd7\x02\n\x0cTesteService\x12\x34\n\x0c\x66indtitleMsg\x12\x13.messages.FindTitle\x1a\x0f.messages.Movie\x12\x41\n\x0f\x66indcategoryMsg\x12\x16.messages.FindCategory\x1a\x16.messages.FindResponse\x12;\n\x0c\x66indactorMsg\x12\x13.messages.FindActor\x1a\x16.messages.FindResponse\x12.\n\tcreateMsg\x12\x10.messages.Create\x1a\x0f.messages.Movie\x12.\n\tupdateMsg\x12\x10.messages.Update\x1a\x0f.messages.Movie\x12\x31\n\tdeleteMsg\x12\x10.messages.Delete\x1a\x12.messages.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocolo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FINDTITLE']._serialized_start=29
  _globals['_FINDTITLE']._serialized_end=55
  _globals['_FINDCATEGORY']._serialized_start=57
  _globals['_FINDCATEGORY']._serialized_end=89
  _globals['_FINDACTOR']._serialized_start=91
  _globals['_FINDACTOR']._serialized_end=117
  _globals['_MOVIE']._serialized_start=120
  _globals['_MOVIE']._serialized_end=369
  _globals['_FINDRESPONSE']._serialized_start=371
  _globals['_FINDRESPONSE']._serialized_end=418
  _globals['_CREATE']._serialized_start=420
  _globals['_CREATE']._serialized_end=475
  _globals['_UPDATE']._serialized_start=477
  _globals['_UPDATE']._serialized_end=533
  _globals['_DELETE']._serialized_start=535
  _globals['_DELETE']._serialized_end=558
  _globals['_RESPONSE']._serialized_start=560
  _globals['_RESPONSE']._serialized_end=583
  _globals['_TESTESERVICE']._serialized_start=586
  _globals['_TESTESERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
